// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhzotvdicqimzlahcwry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoem90dmRpY3FpbXpsYWhjd3J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzM2NTcsImV4cCI6MjA3MzQ0OTY1N30.kOWmIZFRiWVPo05zGZ1awgWwLxRR4v9_8i-9d0w-69w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});